{{- if .Values.podMonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    {{- include "cloud-exporter.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "cloud-exporter.fullname" . }}
spec:
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      {{- include "cloud-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
