apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "cloud-exporter.labels" . | nindent 4 }}
  name: {{ include "cloud-exporter.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloud-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloud-exporter.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "cloud-exporter.serviceAccountName" . }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: aws-metrics-prom-exporter
        ports:
        - containerPort: 2112
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
        {{- with .Values.aws.monitorSubnetIds }}
        - name: AWS_MONITOR_SUBNETS
          value: "{{ . }}"
        {{- end }}
        {{- with .Values.aws.region }}
        - name: AWS_REGION
          value: "{{ . }}"
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
