{{- if .Values.alerts.create -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "cloud-exporter.labels" . | nindent 4 }}
  name: no-free-ip-in-subnet
spec:
  groups:
  - name: NETWORK
    rules:
    - alert: AwsSubnetFreeIps
        annotations:
          message: |
            {{ "{{" }} $labels.subnet {{ "}}" }} has only {{ "{{" }} printf "%.2f" $value {{ "}}" }}% ips free
          summary: Subnet is exhausted
      expr: "(aws_subnet_ips_free/aws_subnet_ips_total)<{{ .Values.alerts.config.subnetIpsFreeThreshold | default 0.1 }}"
{{- end }}
