name: CD

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths-ignore: 
      - 'charts/**'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMG_NAME: steveizzle/aws-metrics-prom-exporter
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=false
          images: ${{ env.REGISTRY }}/${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          # push: ${{ github.event.base_ref =='refs/heads/main' && github.ref_type == 'tag' }}
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

